# Generated by Django 5.2.8 on 2025-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.IntegerField()),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
