# Generated by Django 5.2.8 on 2025-12-14 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_movimientocaja_delete_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.gasto'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('GASTO', 'Gasto'), ('AJUSTE', 'Ajuste Manual')], default='VENTA', max_length=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
