# Generated by Django 4.2.25 on 2025-11-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('venta', 'Venta al Cliente'), ('insumo', 'Consumo Interno')], default='venta', max_length=10)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('codigo_barra', models.CharField(max_length=50, unique=True)),
                ('unidad', models.CharField(default='und', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
