# Generated by Django 4.2.25 on 2025-11-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('shampoo', 'Shampoo'), ('acondicionador', 'Acondicionador'), ('mascarilla', 'Mascarilla / Máscara'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
