# Generated by Django 4.2.25 on 2025-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('shampoo', 'Shampoo'), ('acondicionador', 'Acondicionador'), ('mascarilla', 'Mascarilla / Máscara'), ('aceite', 'Aceite / Aceite'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
