# Generated by Django 4.2.25 on 2025-11-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0002_alter_sucursales_nombre'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina_principal.sucursales'),
        ),
    ]
