# Generated by Django 4.2.25 on 2025-11-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cita_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.IntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1 hora 30 min'), (120, '2 horas'), (150, '2 horas 30 min'), (180, '3 horas'), (210, '3 horas 30 min'), (240, '4 horas'), (270, '4 horas 30 min'), (300, '5 horas'), (330, '5 horas 30 min'), (360, '6 horas'), (390, '6 horas 30 min'), (420, '7 horas'), (450, '7 horas 30 min'), (480, '8 horas'), (510, '8 horas 30 min'), (540, '9 horas'), (570, '9 horas 30 min'), (600, '10 horas')]),
        ),
    ]
