# Generated by Django 5.2.8 on 2025-11-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_cita_cliente_alter_cita_estilista'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
