# Generated by Django 5.2.8 on 2025-12-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cita_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='pagado',
        ),
    ]
