# Generated by Django 4.2.25 on 2025-11-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
