# Generated by Django 4.2.25 on 2025-11-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
