# Generated by Django 4.2.25 on 2025-11-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
