# Generated by Django 4.2.25 on 2025-11-18 18:23

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(default=12345669, help_text='Ingrese un RUT sin puntos. Ej: 12345678-9', max_length=10, unique=True, validators=[usuarios.models.validar_formato_rut, usuarios.models.validar_dv_rut]),
            preserve_default=False,
        ),
    ]
